config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks'
  }

  resources :users do
    get 'profile', on: :collection, as: 'profile'
  end

  root to: 'main#home'
  resources :restaurants do
    resources :dishes
    resources :orders do
      resources :items
    end
  end
end

app/views/shared/_dishes_form.html.erb
<section class='dark:bg-slate-800 bg-white rounded-md px-8 py-6 border border-gray-300 dark:border-gray-700 mb-7'>
  <%= form_with(model: [@restaurant, @dish], local: true, data: { turbo: false }, html: { multipart: true }) do |f| %>
    <% if @dish.errors.any? %>
      <div class='error-alert'>
        <h2 class='font-semibold'>The form contain <%= pluralize(@dish.errors.count, 'error') %></h2>
        <ul class='list-disc p-4'>
        <% @dish.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.label :dish_group, class: 'font-medium dark:text-white text-gray-700' %>
    <%= f.select :dish_group, ['Entrees', 'Soups & Salads', 'Deserts', 'Drink'], {}, class: 'block w-full rounded border-slate-200 dark:border-slate-700 w-full mb-4 mt-2 text-black dark:bg-slate-900 dark:text-white' %>

    <%= f.label :name, class: 'font-medium dark:text-white text-gray-700' %>
    <%= f.text_field :name, class: 'block w-full rounded border-gray-200 dark:border-slate-700 w-full mb-4 mt-2 text-black dark:bg-slate-900 dark:text-white' %>

    <%= f.label :description, class: 'font-medium dark:text-white text-gray-700' %>
    <%= f.text_area :description, rows: 4, class: 'block w-full rounded border-gray-200 dark:border-slate-700 w-full mb-4 mt-2 text-black dark:bg-slate-900 dark:text-white' %>

    <%= f.label :price, class: 'font-medium dark:text-white text-gray-700' %>
    <div class='relative mt-2 rounded-md'>
      <div class='pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3'>
        <span class='text-gray-500 sm:text-sm'>$</span>
      </div>
      <%= f.number_field :price, class: 'block w-full pl-7 rounded border-gray-200 dark:border-slate-700 w-full mb-4 mt-2 text-black dark:bg-slate-900 dark:text-white', step: 0.01 %>
    </div>

    <%= f.label :photo, class: 'font-medium dark:text-white text-gray-700' %>
    <%= f.file_field :photo, class: 'rounded border border-gray-200 dark:border-slate-700 w-full mb-4 mt-2 file:mr-2 file:py-2 file:px-4 file:rounded file:border-0 dark:file:bg-slate-900 dark:file:text-white', accept: 'image/*' %>

    <div class='flex justify-between items-center'>
      <%= link_to '&larr; Back'.html_safe, restaurant_path(@restaurant), class: 'text-blue-600 dark:text-sky-500 hover:underline' %>
      <%= f.submit "#{action_name == 'new' ? 'Create' : 'Update'}", class: 'bg-slate-900 hover:bg-slate-700 dark:bg-sky-500 py-2 px-4 rounded-md dark:hover:bg-sky-400 cursor-pointer transition text-white font-semibold' %>
    </div>
  <% end %>
</section>

app/views/shared/_form.html.erb
<section class="dark:bg-slate-800 bg-white rounded-md px-8 py-6 border border-gray-300 dark:border-gray-700">
  <%= form_with(model: @dish, local: true, data: { turbo: false }, html: { multipart: true }) do |f| %>
    <% if @dish.errors.any? %>
      <div class="bg-red-100 dark:bg-red-900 dark:text-red-100 border dark:border-red-600 border-red-400 text-red-700 px-4 py-3 rounded mb-2">
        <h2 class="font-semibold">The form contain <%= pluralize(@dish.errors.count, "error") %></h2>
        <ul class="list-disc p-4">
        <% @dish.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.label :dish_group, class: 'font-medium dark:text-white text-gray-700' %>
    <%= f.select :dish_group, ["Entrees", "Soups & Salads", "Deserts", "Drink"], {}, class: 'block w-full rounded border-slate-200 dark:border-slate-700 w-full mb-4 mt-2 text-black dark:bg-slate-900 dark:text-white' %>

    <%= f.label :name, class: 'font-medium dark:text-white text-gray-700' %>
    <%= f.text_field :name, class: 'block w-full rounded border-gray-200 dark:border-slate-700 w-full mb-4 mt-2 text-black dark:bg-slate-900 dark:text-white' %>

    <%= f.label :description, class: 'font-medium dark:text-white text-gray-700' %>
    <%= f.text_area :description, rows: 4, class: 'block w-full rounded border-gray-200 dark:border-slate-700 w-full mb-4 mt-2 text-black dark:bg-slate-900 dark:text-white' %>

    <%= f.label :price, class: 'font-medium dark:text-white text-gray-700' %>
    <div class="relative mt-2 rounded-md">
      <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
        <span class="text-gray-500 sm:text-sm">$</span>
      </div>
      <%= f.number_field :price, class: 'block w-full pl-7 rounded border-gray-200 dark:border-slate-700 w-full mb-4 mt-2 text-black dark:bg-slate-900 dark:text-white' %>
    </div>

    <%= f.label :photo, class: 'font-medium dark:text-white text-gray-700' %>
    <%= f.file_field :photo, class: 'rounded border border-gray-200 dark:border-slate-700 w-full mb-4 mt-2 file:mr-2 file:py-2 file:px-4 file:rounded file:border-0 dark:file:bg-slate-900 dark:file:text-white', accept: 'image/*' %>

    <div class="flex justify-between items-center">
      <% if action_name == 'new' %>
        <%= link_to "&larr; Back".html_safe, dishes_path, class: 'text-blue-600 dark:text-sky-500 hover:underline' %>
      <% elsif action_name == 'edit' %>
        <%= link_to "&larr; Back".html_safe, dish_path(@dish), class: 'text-blue-600 dark:text-sky-500 hover:underline' %>
      <% end %>
      
      <%= f.submit "#{action_name == 'new' ? 'Create' : 'Update'}", class: 'bg-slate-900 hover:bg-slate-700 dark:bg-sky-500 py-2 px-4 rounded-md dark:hover:bg-sky-400 cursor-pointer transition text-white font-semibold' %>
    </div>
  <% end %>
</section>

app/views/shared/_items_form.html.erb
<section class='dark:bg-slate-800 bg-white rounded-md px-8 py-6 border border-gray-300 dark:border-gray-700 mb-7'>
  <%= form_with(model: [@restaurant, @order, @item], local: true, data: { turbo: false }, html: { multipart: true }) do |f| %>
    <% if @item.errors.any? %>
      <div class='error-alert'>
        <h2 class='font-semibold'>The form contain <%= pluralize(@item.errors.count, 'error') %></h2>
        <ul class='list-disc p-4'>
          <% @item.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <% if @restaurant.dishes.any? %>
      <h2 class='heading-2 mb-4'>Items</h2>
      <%= f.label :dish_id, class: 'font-medium dark:text-white text-gray-700' %>
      <%= f.select :dish_id, options_for_select(@restaurant.dishes.map { |dish| [dish.name, dish.id] }), {}, class: 'block w-full rounded border-slate-200 dark:border-slate-700 w-full mb-4 mt-2 text-black dark:bg-slate-900 dark:text-white' %>
      <% if @selected_dish %>
        <%= f.hidden_field :price, value: @selected_dish.price %>
      <% end %>
    <% else %>
      <p class='font-medium text-center'>No dishes available to add to this order.
      <%= link_to 'Create a new dish', new_restaurant_dish_path(@restaurant), class: 'underline' %>
      </p>
    <% end %>

    <div class='flex justify-between items-center'>
      <%= link_to '&larr; Back'.html_safe, restaurant_path(@restaurant), class: 'text-blue-600 dark:text-sky-500 hover:underline' %>
      <%= f.submit "#{action_name == 'new' ? 'Create' : 'Update'}", class: 'bg-slate-900 hover:bg-slate-700 dark:bg-sky-500 py-2 px-4 rounded-md dark:hover:bg-sky-400 cursor-pointer transition text-white font-semibold' %>
    </div>
  <% end %>
</section>

app/views/shared/_orders_form.html.erb
<% content_for :title, 'Create order' %>

<section class='dark:bg-slate-800 bg-white rounded-md px-8 py-6 border border-gray-300 dark:border-gray-700 mb-7'>
  <%= form_with(model: [@restaurant, @order], local: true, data: { turbo: false }, html: { multipart: true }) do |f| %>
    <% if @order.errors.any? %>
      <div class='error-alert'>
        <h2 class='font-semibold'>The form contain <%= pluralize(@order.errors.count, 'error') %></h2>
        <ul class='list-disc p-4'>
          <% @order.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.label :taxes, 'Taxes %', class: 'font-medium dark:text-white text-gray-700' %>
    <%= f.number_field :taxes, class: 'block w-full rounded border-gray-200 dark:border-slate-700 w-full mb-4 mt-2 text-black dark:bg-slate-900 dark:text-white' %>

  <div class='flex justify-between items-center'>
    <%= link_to '&larr; Back'.html_safe, restaurant_orders_path(@restaurant, @orders), class: 'text-blue-600 dark:text-sky-500 hover:underline' %>
    <%= f.submit "#{action_name == 'new' ? 'Create' : 'Update'}", class: 'bg-slate-900 hover:bg-slate-700 dark:bg-sky-500 py-2 px-4 rounded-md dark:hover:bg-sky-400 cursor-pointer transition text-white font-semibold' %>
  </div>
  <% end %>
</section>

app/views/shared/_restaurants_form.html.erb
<article class='dark:bg-slate-800 bg-white rounded-md px-8 py-6 border border-gray-300 dark:border-gray-700 mb-7'>
  <%= form_with(model: @restaurant, local: true, data: { turbo: false }, html: { multipart: true }) do |f| %>
    <% if @restaurant.errors.any? %>
      <div class='bg-red-100 dark:bg-red-900 dark:text-red-100 border dark:border-red-600 border-red-400 text-red-700 px-4 py-3 rounded mb-2'>
        <h2 class='font-semibold'>The form contain <%= pluralize(@restaurant.errors.count, 'error') %></h2>
        <ul class='list-disc p-4'>
        <% @restaurant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.label :name, class: 'font-medium dark:text-white text-gray-700' %>
    <%= f.text_field :name, class: 'block w-full rounded border-gray-200 dark:border-slate-700 w-full mb-4 mt-2 text-black dark:bg-slate-900 dark:text-white' %>

    <%= f.label :description, class: 'font-medium dark:text-white text-gray-700' %>
    <%= f.text_area :description, rows: 4, class: 'block w-full rounded border-gray-200 dark:border-slate-700 w-full mb-4 mt-2 text-black dark:bg-slate-900 dark:text-white' %>

    <%= f.label :address, class: 'font-medium dark:text-white text-gray-700' %>
    <%= f.text_field :address, class: 'block w-full rounded border-gray-200 dark:border-slate-700 w-full mb-4 mt-2 text-black dark:bg-slate-900 dark:text-white' %>

    <%= f.label :phone_number, class: 'font-medium dark:text-white text-gray-700' %>
    <%= f.telephone_field :phone_number, class: 'block w-full rounded border-gray-200 dark:border-slate-700 w-full mb-4 mt-2 text-black dark:bg-slate-900 dark:text-white' %>

    <%= f.label :logo, class: 'font-medium dark:text-white text-gray-700' %>
    <%= f.file_field :logo, class: 'rounded border border-gray-200 dark:border-slate-700 w-full mb-4 mt-2 file:mr-2 file:py-2 file:px-4 file:rounded file:border-0 dark:file:bg-slate-900 dark:file:text-white', accept: 'image/*' %>

    <div class='flex justify-between items-center'>
      <%= link_to '&larr; Back'.html_safe, restaurants_path, class: 'text-blue-600 dark:text-sky-500 hover:underline' %>
      <%= f.submit "#{action_name == 'new' ? 'Create' : 'Update'}", class: 'bg-slate-900 hover:bg-slate-700 dark:bg-sky-500 py-2 px-4 rounded-md dark:hover:bg-sky-400 cursor-pointer transition text-white font-semibold' %>
    </div>
  <% end %>
</article>