config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks'
  }

  resources :users do
    get 'profile', on: :collection, as: 'profile'
  end

  root to: 'main#home'
  resources :restaurants do
    resources :dishes
    resources :orders do
      resources :items
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :restaurant
  has_many :items

  accepts_nested_attributes_for :items
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @restaurant = Restaurant.find(params[:restaurant_id])
    @orders = @restaurant.orders
  end

  def show
    @restaurant = Restaurant.find(params[:restaurant_id])
    @order = @restaurant.orders.find(params[:id])
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @order = @restaurant.orders.build
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @order = @restaurant.orders.build(order_params)
    if @order.save
      redirect_to restaurant_orders_path(@restaurant, @order)
    else
      render 'new'
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @order = @restaurant.orders.find(params[:id])
    @order.destroy

    redirect_to restaurant_orders_path(@restaurant)
  end

  private

  def order_params
    params.require(:order).permit(:date, :sub_total, :taxes, :total)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<% content_for :title, @restaurant.name %>

<%= link_to '&larr; Back to restaurant'.html_safe, restaurant_path(@restaurant), class: 'text-blue-600 dark:text-sky-500 hover:underline' %>

<section class='mb-7 mt-3 flex justify-between items-center'>
  <h1 class='heading-1'><%= @restaurant.name %> orders</h1>
  <%= link_to 'Create order', new_restaurant_order_path(@restaurant), class: 'btn-primary' %>
</section>

<% if @restaurant.orders.any? %>
  <section class='overflow-auto rounded border border-gray-300 dark:border-gray-700 mb-10'>
    <table class='w-full'>
      <thead class='bg-gray-100 border-b-2 border-gray-300 dark:bg-slate-800 dark:border-slate-600'>
        <tr class='[&>th]:text-gray-300'>
              <th class='p-3 font-semibold tracking-wide text-left'>Order #</th>
              <th class='p-3 font-semibold tracking-wide text-left'>Date</th>
              <th class='p-3 font-semibold tracking-wide text-left'>Total</th>
              <th colspan='3' class='p-3 font-semibold tracking-wide text-left'>Actions</th>
          </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
          <tr class='border-b border-gray-300 dark:border-gray-700 [&>td]:dark:text-white'>
            <td class='p-3 whitespace-nowrap font-semibold'><%= order.id %></td>
            <td class='p-3 whitespace-nowrap'><%= l order.date, format: :long %></td>
            <td class='p-3 whitespace-nowrap'><%= number_to_currency(order.total) %></td>
            <td class='pl-3 whitespace-nowrap'>
              <%= link_to restaurant_order_path(@restaurant, order) do %>
                <svg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 24 24' stroke-width='1.5' stroke='currentColor' class='w-6 h-6'>
                  <path stroke-linecap='round' stroke-linejoin='round' d='M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z' />
                  <path stroke-linecap='round' stroke-linejoin='round' d='M15 12a3 3 0 11-6 0 3 3 0 016 0z' />
                </svg>
              <% end %>
            </td>
            <td class='pl-3 whitespace-nowrap'>
              <svg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 24 24' stroke-width='1.5' stroke='currentColor' class='w-6 h-6'>
                <path stroke-linecap='round' stroke-linejoin='round' d='M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10' />
              </svg>
            </td>
            <td class='pl-3 whitespace-nowrap'>
              <%= button_to restaurant_order_path(@restaurant, order), method: :delete, form: { data: { turbo_confirm: 'Are you sure you want to delete this order?' } } do %>
                <svg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 24 24' stroke-width='1.5' stroke='currentColor' class='w-6 h-6'>
                  <path stroke-linecap='round' stroke-linejoin='round' d='M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0' />
                </svg>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </section>
<% else %>
  <p class='font-medium text-gray-700 dark:text-gray-400 text-center'>No orders created yet.</p>
<% end %>

app/views/orders/new.html.erb
<h1 class='text-3xl font-bold mb-6'>Create order</h1>

<%= render 'shared/orders_form' %>

app/views/orders/show.html.erb
<% content_for :title, @restaurant.name %>

<%= link_to '&larr; Back to orders'.html_safe, restaurant_orders_path(@restaurant, @orders), class: 'text-blue-600 dark:text-sky-500 hover:underline' %>

<section class='mb-7 mt-3 flex justify-between items-center'>
  <h1 class='text-3xl font-bold'>Order #<%= @order.id %></h1>
  <%= link_to 'Add item', new_restaurant_order_item_path(@restaurant, @order), class: 'btn-primary' %>
</section>

<% if @order.items.any? %>
  <section class='overflow-auto rounded border border-gray-300 dark:border-gray-700 mb-10'>
    <table class='w-full text-left'>
      <thead class='bg-gray-100 border-b-2 border-gray-300 dark:bg-slate-800 dark:border-slate-600'>
        <tr>
          <th scope='col' class='p-3 font-semibold'>
            <span class='sr-only'></span>
          </th>
          <th scope='col' class='p-3 font-semibold'>Dish</th>
          <th scope='col' class='p-3 font-semibold'>Price</th>
          <th scope='col' colspan='3' class='p-3 font-semibold'>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @order.items.each do |item| %>
          <% dish = Dish.find(item.dish_id) %>
          <tr class='border-b border-gray-300 dark:border-gray-700'>
            <td class='p-3'>
                <%= image_tag(url_for(dish.photo), alt: dish.name, size: '250x250') %>
            </td>
            <td class='p-3 whitespace-nowrap'>
                <p><%= dish.name %></p>
            </td>
            <td class='p-3 whitespace-nowrap'><%= number_to_currency(item.price) %></td>
            <td class='p-3 whitespace-nowrap'>
              <%= link_to restaurant_dish_path(@restaurant, dish) do %>
                <svg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 24 24' stroke-width='1.5' stroke='currentColor' class='w-6 h-6'>
                  <path stroke-linecap='round' stroke-linejoin='round' d='M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z' />
                  <path stroke-linecap='round' stroke-linejoin='round' d='M15 12a3 3 0 11-6 0 3 3 0 016 0z' />
                </svg>
              <% end %>
            </td>
            <td class='p-3 whitespace-nowrap'>
              <svg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 24 24' stroke-width='1.5' stroke='currentColor' class='w-6 h-6'>
                <path stroke-linecap='round' stroke-linejoin='round' d='M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10' />
              </svg>
            </td>
            <td class='p-3 whitespace-nowrap'>
              <%= button_to restaurant_order_path(@restaurant, item), method: :delete, form: { data: { turbo_confirm: 'Are you sure you want to delete this order?' } } do %>
                <svg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 24 24' stroke-width='1.5' stroke='currentColor' class='w-6 h-6'>
                  <path stroke-linecap='round' stroke-linejoin='round' d='M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0' />
                </svg>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </section>
<% else %>
  <p class='font-medium text-gray-700 dark:text-gray-400 text-center'>No items in this order.
  <%= link_to 'Add item', new_restaurant_order_item_path(@restaurant, @order), class: 'underline' %>
  </p>
<% end %>