config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks'
  }

  resources :users do
    get 'profile', on: :collection, as: 'profile'
  end

  root to: 'main#home'
  resources :restaurants do
    resources :dishes
    resources :orders do
      resources :items
    end
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :dishes, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :name, presence: true, length: { minimum: 2, maximum: 35 }
  validates :description, presence: true, length: { minimum: 5, maximum: 500 }
  validates :address, presence: true, length: { minimum: 2, maximum: 150 }
  validates :phone_number, presence: true, numericality: true, length: { minumum: 10, maximum: 10 }
  validates :logo, presence: true

  has_one_attached :logo
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @dishes = @restaurant.dishes
    @new_dish = Dish.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save && params[:restaurant][:logo].present?
      @restaurant.logo.attach(params[:restaurant][:logo])
      redirect_to restaurants_path
    else
      render 'new'
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])

    if @restaurant.update(restaurant_params)
      redirect_to @restaurant
    else
      render 'edit'
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :address, :phone_number, :logo)
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/edit.html.erb
<% content_for :title, 'Update restaurant' %>

<h1 class='text-3xl font-bold mb-6'>Update restaurant</h1>

<%= render 'shared/restaurants_form' %>

app/views/restaurants/index.html.erb
<% content_for :title, 'All restaurants' %>

<section class='flex sm:flex-row justify-between items-center mb-7 flex-col gap-4'>
  <h1 class='heading-1'>Restaurants</h1>
  <%= link_to 'Add restaurant', new_restaurant_path, class: 'btn-primary' %>
</section>

<% if @restaurants.any? %>
  <article class='grid md:grid-cols-2 xl:grid-cols-3 gap-8 mb-7'>
    <% @restaurants.each do |restaurant| %>
      <%= link_to restaurant_path(restaurant) do %>
        <section class='rounded overflow-hidden bg-white dark:bg-slate-800 border border-gray-300 dark:border-gray-700'>
          <div class='h-[250px]'>
            <%= image_tag(url_for(restaurant.logo), alt: restaurant.name, class: 'w-full h-full object-cover') %>
          </div>
            <h2 class='font-medium text-xl text-center py-2'><%= restaurant.name %></h2>
        </section>
      <% end %>
    <% end %>
  </article>
<% else %>
  <p class='font-medium text-gray-700 dark:text-gray-400 text-center'>No restaurants created yet.</p>
<% end %>

app/views/restaurants/new.html.erb
<h1 class='text-3xl font-bold mb-6'>Create restaurant</h1>

<%= render 'shared/restaurants_form' %>

app/views/restaurants/show.html.erb
<% content_for :title, @restaurant.name %>

<section class='mb-7 mt-3 flex justify-between items-center'>
  <h1 class='heading-1'><%= @restaurant.name %></h1>
  <%= link_to 'Go to orders &rarr;'.html_safe, restaurant_orders_path(@restaurant), class: 'text-black px-4 py-2 rounded font-semibold bg-gray-100 hover:bg-white' %>
</section>

<article class='flex flex-col md:flex-row md:h-[450px] bg-white dark:bg-slate-900 rounded-lg overflow-hidden border border-gray-300 dark:border-gray-700 mb-7'>
  <%= image_tag(url_for(@restaurant.logo), alt: @restaurant.name, class: 'w-full md:w-1/3 object-cover h-[350px] md:h-full') %>
  <div class='p-5 flex flex-col justify-between w-full md:w-2/3'>
    <section>
      <p class='mb-7'><%= @restaurant.description %></p>

      <div class='flex gap-2 mb-3'>
        <span>
          <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='currentColor' class='w-4 h-4 flex-shrink-0 align-middle inline-block'>
            <path fill-rule='evenodd' d='M11.54 22.351l.07.04.028.016a.76.76 0 00.723 0l.028-.015.071-.041a16.975 16.975 0 001.144-.742 19.58 19.58 0 002.683-2.282c1.944-1.99 3.963-4.98 3.963-8.827a8.25 8.25 0 00-16.5 0c0 3.846 2.02 6.837 3.963 8.827a19.58 19.58 0 002.682 2.282 16.975 16.975 0 001.145.742zM12 13.5a3 3 0 100-6 3 3 0 000 6z' clip-rule='evenodd' />
          </svg>
        </span>

        <span>
          <p class='align-middle inline-block'><%= @restaurant.address %></p>
        </span>
      </div>

      <div class='flex items-center gap-2'>
        <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='currentColor' class='w-4 h-4 flex-shrink-0'>
          <path fill-rule='evenodd' d='M1.5 4.5a3 3 0 013-3h1.372c.86 0 1.61.586 1.819 1.42l1.105 4.423a1.875 1.875 0 01-.694 1.955l-1.293.97c-.135.101-.164.249-.126.352a11.285 11.285 0 006.697 6.697c.103.038.25.009.352-.126l.97-1.293a1.875 1.875 0 011.955-.694l4.423 1.105c.834.209 1.42.959 1.42 1.82V19.5a3 3 0 01-3 3h-2.25C8.552 22.5 1.5 15.448 1.5 6.75V4.5z' clip-rule='evenodd' />
        </svg>
        <p><%= number_to_phone(@restaurant.phone_number, delimiter: ' ', pattern: /(\d{2})(\d{4})(\d{4})$/) %></p>
      </div>
    </section>

    <section class='flex justify-end gap-2 mt-4'>
      <%= link_to edit_restaurant_path, class: 'bg-slate-900 dark:bg-sky-500 rounded-md p-2' do %>
        <svg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 24 24' stroke-width='1.5' stroke='white' class='w-6 h-6'>
          <path stroke-linecap='round' stroke-linejoin='round' d='M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10' />
        </svg>
      <% end %>

      <%= button_to @restaurant, method: :delete, class: 'bg-slate-900 dark:bg-sky-500 rounded-md p-2', form: { data: { turbo_confirm: 'Are you sure you want to delete this dish?' } } do %>
        <svg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 24 24' stroke-width='1.5' stroke='white' class='w-6 h-6'>
          <path stroke-linecap='round' stroke-linejoin='round' d='M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0' />
        </svg>
      <% end %>
    </section>
  </div>
</article>

<section class='flex justify-between items-center mb-7 mt-3'>
  <h1 class='heading-2'>Dishes</h1>
  <%= link_to 'Create dish', new_restaurant_dish_path(@restaurant), class: 'btn-primary' %>
</section>

<% if @dishes.any? %>
  <article class='grid md:grid-cols-2 xl:grid-cols-3 gap-10 mb-20'>
    <% @dishes.each do |dish| %>
      <%= link_to restaurant_dish_path(@restaurant, dish) do %>
        <section class='rounded overflow-hidden bg-white dark:bg-slate-800 border border-gray-300 dark:border-gray-700'>
          <div class='h-[250px]'>
            <%= image_tag(url_for(dish.photo), alt: dish.name, class: 'w-full h-full object-cover') %>
          </div>
            <h2 class='font-medium text-xl text-center py-2'><%= dish.name %></h2>
        </section>
      <% end %>
    <% end %>
  </article>
<% else %>
  <p class='font-medium text-gray-700 dark:text-gray-400 text-center'>No dishes created yet.</p>
<% end %>